name: grievance-analytics
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.11
  - pandas
  - sqlalchemy
  - fastapi
  - uvicorn
  - requests
  - psycopg2
  - boto3
  - python-dotenv
  - loguru
  - tqdm
  - pydantic
  - pydantic-settings
  - pip
  - ipykernel
  - conda-lock
  - pip:
    - schedule
    - httpx
    - starlette
    - anyio
    - click
    - packaging
    - typing-extensions
    - -e .