"""ORTPS topic-modeling profile (stopwords + adaptive parameter policy)."""

from __future__ import annotations

from app.pipelines.shared.topic_modeling.bertopic_engine import TopicModelParams

# Odisha-specific stopwords for ORTPS grievance analysis.
# Filters generic complaint language to surface category-specific themes.
ORTPS_STOPWORDS = [
    # Poverty & socioeconomic language
    "poor",
    "family",
    "belongs",
    "belong",
    "bpl",
    "poverty",
    "economic",
    "weaker",
    "section",
    "background",
    "financially",
    "needy",
    "helpless",
    # Petition boilerplate
    "sir",
    "madam",
    "dear",
    "respected",
    "honorable",
    "honourable",
    "humble",
    "humbly",
    "submission",
    "kindly",
    "please",
    "request",
    "pray",
    "appeal",
    "faithfully",
    "obediently",
    "thanking",
    "thanks",
    "yours",
    # Generic administrative terms
    "office",
    "department",
    "district",
    "block",
    "village",
    "panchayat",
    "gram",
    "tahasil",
    "tahsil",
    "govt",
    "government",
    "authority",
    "concerned",
    "officer",
    "collector",
    "bdo",
    "sub",
    "matter",
    "issue",
    "problem",
    "regarding",
    "subject",
    "case",
    "letter",
    "application",
    "form",
    "grievance",
    "complaint",
    "petition",
    "representation",
    "dated",
    "date",
    "reference",
    "ref",
    "copy",
    "enclosed",
    "attachment",
    "document",
    # Generic action verbs
    "give",
    "provide",
    "sanction",
    "approve",
    "allot",
    "allotment",
    "help",
    "assist",
    "resolve",
    "solve",
    "grant",
    "issue",
    "submit",
    "apply",
    "applied",
    "file",
    "filed",
    "visit",
    "visited",
    "check",
    "verify",
    # Common abbreviations
    "pm",
    "pmay",
    "pmgsy",
    "mgnrega",
    "nrega",
    "aay",
    "po",
    "ps",
    "dist",
    "pin",
    "mob",
    "mobile",
    # Odisha place names (major cities/districts)
    "bhubaneswar",
    "cuttack",
    "puri",
    "berhampur",
    "sambalpur",
    "balasore",
    "bhadrak",
    "dhenkanal",
    "angul",
    "bargarh",
    "bolangir",
    "kalahandi",
    "kandhamal",
    "kendrapara",
    "keonjhar",
    "khordha",
    "koraput",
    "malkangiri",
    "mayurbhanj",
    "nabarangpur",
    "nayagarh",
    "nuapada",
    "rayagada",
    "sonepur",
    "sundargarh",
    "odisha",
    "orissa",
    # Generic time references
    "year",
    "month",
    "day",
    "time",
    "ago",
    "since",
    "long",
    "till",
    "until",
]


def get_ortps_topic_model_params(n_samples: int) -> TopicModelParams:
    """Adaptive BERTopic parameters used by ORTPS analysis."""
    if n_samples < 1000:
        return TopicModelParams(
            min_cluster_size=30,
            min_samples=10,
            top_n_words=12,
            n_components=3,
            min_df=1,
            max_df=1.0,
            calculate_probabilities=True,
        )

    if n_samples < 5000:
        return TopicModelParams(
            min_cluster_size=50,
            min_samples=15,
            top_n_words=10,
            n_components=5,
            min_df=1,
            max_df=1.0,
            calculate_probabilities=True,
        )

    return TopicModelParams(
        min_cluster_size=100,
        min_samples=30,
        top_n_words=10,
        n_components=5,
        min_df=2,
        max_df=1.0,
        calculate_probabilities=False,
    )

